### ISSUE TITLE
ROS 2 port

### ISSUE THREAD

**Issue by dirk-thomas** [WPI-RAIL/rosauth#16]
We (OSRF) would like to contribute a ROS 2 port of this package. Commonly we prefer to create a `ros2` branch in the upstream repository in order to keep the code as close as possible to the ROS 1 code and ease porting of patches between the branches.

I just wanted to check if the maintainers of this repo would be open to this? This could either be done by creating a `ros2` branch for us and we create PRs or (if you would be comfortable with giving us write access) we could move forward on this without requiring your attention for future PRs (we would still go through PRs).

Otherwise we would need to create a fork of the repo (which is more difficult to discover and sometime unclear to users which repo to use).

**Comment by rctoris** [comment]
That sounds great Dirk. I'll make the branch now. I can give external collaborator access as well for this repo if you give a list of developers to add.

**Comment by dirk-thomas** [comment]
> I'll make the branch now.

Great - thanks.

> I can give external collaborator access as well for this repo if you give a list of developers to add.

Let's start with me and we will see if we need more in the future.

I will likely ask for the same on the `async_web_server_cpp` in a bit :wink:

**Comment by rctoris** [comment]
Done.
