### ISSUE TITLE
Lack of documentation and cannot authenticate

### ISSUE THREAD

**Issue by naimen** [WPI-RAIL/rosauth#28]
I'm setting up a rosbridge websocket that should authenticate the clients to harden security. The rosbridge already comes with authentication mechanism, which points to this project. 

Here I face the first problem, it's very difficult to find information about how the authentication is performed or how should this service be used. After some digging I found this issue that explained a bit of how this works. (https://github.com/GT-RAIL/rosauth/issues/3)
Still it's unclear to me how exactly to construct the authentication request, there's no information regarding which digest the MAC should be, or which message is MAC calculated for. After further digging by looking into the source code, it seems that the digest is SHA-512 and the message is the concatenation of secret and values from the authentication request.

With this knowledge I tried to authenticate by calling /authenticate manually using the following setup.
secret:
`f1JlG2fNnJIHgjnL`

request:
`client: '' 
dest: ''
rand: 'random'
t: {secs: 0, nsecs: 0}
level: ''
end: {secs: 0, nsecs: 0}`

The MAC should therefore be the SHA-512 digest of `f1JlG2fNnJIHgjnLrandom00`, which is 
`01C0D1F9FB2E945DFE8E19F66072BFC2115518E81D805BCBA6F427D94995181D6725DF71B74C536B1CC43D5133E1CEB81999DA2AA2768CA20363DFB6797B941E`

Complete call to the service is
`rosservice call /authenticate "mac: '01C0D1F9FB2E945DFE8E19F66072BFC2115518E81D805BCBA6F427D94995181D6725DF71B74C536B1CC43D5133E1CEB81999DA2AA2768CA20363DFB6797B941E'
client: ''
dest: ''
rand: 'random'
t: {secs: 0, nsecs: 0}
level: ''
end: {secs: 0, nsecs: 0}"`

But the service returns
`authenticated: False`

Any help or suggestions will be appreciated
Thanks in advance

**Comment by reinzor** [comment]
Hi,

I will try to update the ROS wiki in the coming weeks. In the meantime I could give an example on how we are currently using `rosauth`.

Javascript (roslibjs side):

```javascript
let secret = 'myawesomesecret1'
let dest = this.url
let rand = randomString(10)
let time = new Date().getTime() / 1000
let timeEnd = time + 1000
let level = "admin"
let mac = sha512(secret + client.getUA() + dest + rand + parseInt(time).toString() + level + parseInt(timeEnd).toString())  // using sha512 library js-sha512 and client library clientjs
this.authenticate(mac, client.getUA(), dest, rand, time, level, timeEnd)  // method from roslibjs
```

Server side (`rosauth`) `auth.secret`:

```
myawesomesecret1
```

```xml
<node name="authentication" pkg="rosauth" type="ros_mac_authentication">
  <param name="allowed_time_delta" value="-1" /> <!-- Disable time check (optional if you want to get it to work with a simulation time) -->
  <param name="secret_file_location" value="$PATH_TO_SECRET_FOLDER/auth.secret" />
</node>
```

Could you try this set-up?

**Comment by reinzor** [comment]
I also tried your example:

```bash
rosservice call /authenticate "{mac: '01c0d1f9fb2e945dfe8e19f66072bfc2115518e81d805bcba6f427d94995181d6725df71b74c536b1cc43d5133e1ceb81999da2aa2768ca20363dfb6797b941e', client: '', dest: '', rand: 'random', t: {secs: 0, nsecs: 0}, level: '', end: {secs: 0, nsecs: 0}}"
/opt/ros/melodic/lib/python2.7/dist-packages/rosservice/__init__.py:607: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  service_args.append(yaml.load(arg))
authenticated: True
```

So one possible difference is that you did not set the `allowed_time_delta` to `-1` and another difference that I do not capitalize the hash.

**Comment by naimen** [comment]
Thank you very much, you example works :)

I think the capitalization of the hash is the cause of failure from my example, i tried your example with default time_delta and it works.

**Comment by reinzor** [comment]
Added documentation on http://wiki.ros.org/rosauth

**Comment by alerena** [comment]
Hi, I tried the authentication in my ros application, but even with your exemple in documentation the response is always False.

This are the commands that I use:

`rosrun rosauth ros_mac_authentication _secret_file_location:=/home/edo/secret/secret _allowed_time_delta:=-1`

The secret is "1234567890abcdef"

then I launch a bash file.

`#!/bin/bash`
`hash=$(echo -n "1234567890abcdefclientdestrand0level0" | sha512sum)`
`echo $hash`
`hash=$(echo "$hash" | cut -c -128)`
`echo $hash`
`echo "{mac: '$hash', client: 'client', dest: 'dest', rand: 'rand', t: {sec: 0, nsec: 0}, level: 'level', end: {sec: 0, nsec: 0}}"`
`output=$(rosservice call /authenticate "{mac: '19d9d2166799f1ffd6fee6379f957502aff8716bfebc8cc8b3bac57ade14441bb9678be89d0a7eec9c81291f854d754d7a4de2278bede56f162c2faeb468c68a', client: 'client', dest: 'dest', rand: 'rand', t: {secs: 0, nsecs: 0}, level: 'level', end: {secs: 0, nsecs: 0}}")`
`echo $output`

the response is always 

`0 0 authenticated: False`

I also compared the hash in the documentation with my hash and it's the same.

I also tried with my JS application to laung the ros.authenticate(...) function, the result is the same.

I laso tried with manually launch the service, writing the hash but not work.

I use kinetic ros.

**Comment by reinzor** [comment]
I tried your script in my `noetic` and `melodic` environment and it seems to authenticate. Cannot test this on `kinetic` but I don't know why it shouldn't work. Try updating your ROS release would be my advice since Kinetic is EOL.

**Comment by jstiefel** [comment]
Hi, 

Thanks for adding the documentation. I have some follow up questions to your example.

According to the [Ros class](http://robotwebtools.org/jsdoc/roslibjs/current/Ros.html), `client` and `dest` should be IPs. But a method `client.getUA()` doesn't exist in clientjs. The existing method `getUserAgent()` does not return an IP. How do you get the IP of the client?

Is there a way to know if authentication was successful?

And could you provide the function of `randomString()`?

Thank you.
