### ISSUE TITLE
Foxy Release?

### ISSUE THREAD

**Issue by JWhitleyWork** [WPI-RAIL/rosauth#31]
Looks like this package is a dependency for releasing https://github.com/RobotWebTools/rosbridge_suite/ to Foxy. Could we get a release of this package for Foxy? Looks like @dirk-thomas did the last ROS2 release.

**Comment by dirk-thomas** [comment]
I only did the past releases to bootstrap the transition of this repo to ROS 2 and am not maintaining these packages. Maybe @reinzor can do ROS 2 releases going forward?

**Comment by reinzor** [comment]
We are not actively using ROS2 so I cannot really verify that everything works. However, I could do a release if you could verify that everything is working properly @JWhitleyWork

**Comment by JWhitleyWork** [comment]
@reinzor Please see #32. This works on both Dashing and Foxy (but won't work on G-turtle due to deprecated launch parameters for nodes). After this merge, a release for Foxy would be appreciated.

**Comment by reinzor** [comment]
@JWhitleyWork , thanks for the update. Released a new patch version on the `ros2` branch. However, I cannot create a `bloom-release` due to permission errors:

```
ERROR: Permission to ros2-gbp/rosauth-release.git denied to reinzor.
```

Or should I use `https://github.com/gt-rail-release/rosauth-release.git`? Don't know why this has changed for `ros2`.

@dirk-thomas , could you help me with this?

**Comment by dirk-thomas** [comment]
> could you help me with this?

Sorry, I am not working on ROS anymore [[1](https://discourse.ros.org/t/thank-you-farewell/17297)]. Maybe someone from the @ros2/team can help you. (I guess I am unable to mention a team I am not part of anymore, so @nuclearsandwich)

**Comment by nuclearsandwich** [comment]
Thanks for the handoff Dirk. I'll get @reinzor set up.

**Comment by reinzor** [comment]
Thanks, created a release PR: https://github.com/ros/rosdistro/pull/27767

**Comment by JWhitleyWork** [comment]
Thank you!
